// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    China: typeof import('./src/components/MapShow/China.vue')['default']
    ChinaModel: typeof import('./src/components/MapShow/childComps/ChinaModel.vue')['default']
    Container: typeof import('./src/components/Base/Container.vue')['default']
    Cpu: typeof import('@/components/SideBar/Child/Cpu.vue')['default']
    DataTransport: typeof import('@/components/SideBar/Child/DataTransport.vue')['default']
    Disk: typeof import('@/components/SideBar/Child/Disk.vue')['default']
    Earth: typeof import('./src/components/MapShow/Earth.vue')['default']
    EarthChina: typeof import('./src/components/MapShow/EarthChina.vue')['default']
    EarthChinaModel: typeof import('./src/components/MapShow/childComps/earthChinaModel.vue')['default']
    EarthModel: typeof import('./src/components/MapShow/childComps/EarthModel.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    GroundStation: typeof import('@/components/SideBar/Child/GroundStation.vue')['default']
    GroundStationInfo: typeof import('@/components/SideBar/Child/GroundStationInfo.vue')['default']
    Header: typeof import('./src/components/Base/Header.vue')['default']
    Home: typeof import('./src/views/Home.vue')['default']
    MapShow: typeof import('./src/components/Base/MapShow.vue')['default']
    Memory: typeof import('@/components/SideBar/Child/Memory.vue')['default']
    MizarBreadcrumb: typeof import('./src/components/Base/MizarBreadcrumb.vue')['default']
    Navigation: typeof import('./src/components/Base/Navigation.vue')['default']
    SatelliteList: typeof import('@/components/SideBar/Child/SatelliteList.vue')['default']
    SideBar: typeof import('./src/components/Base/SideBar.vue')['default']
    SpaceGoal: typeof import('@/components/SideBar/Child/SpaceGoal.vue')['default']
    SpaceTarget: typeof import('./src/components/SideBar/SpaceTarget.vue')['default']
    StationState: typeof import('./src/components/Base/StationState.vue')['default']
    StatusBar: typeof import('./src/components/MapShow/childComps/StatusBar.vue')['default']
    TimingCenter: typeof import('./src/components/SideBar/TimingCenter.vue')['default']
    Title: typeof import('./src/components/Base/Title.vue')['default']
    TrackLegend: typeof import('./src/components/MapShow/childComps/TrackLegend.vue')['default']
    WarningDisposal: typeof import('@/components/SideBar/Child/WarningDisposal.vue')['default']
    WorkingStatus: typeof import('./src/components/SideBar/WorkingStatus.vue')['default']
  }
}

export { }
