// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./src/components/Base/Breadcrumb.vue')['default']
    Container: typeof import('./src/components/Base/Container.vue')['default']
    DataTransport: typeof import('./src/components/DataTransport.vue')['default']
    DiskUsage: typeof import('./src/components/DiskUsage.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    GroundStation: typeof import('./src/components/GroundStation.vue')['default']
    GroundStationInfo: typeof import('./src/components/GroundStationInfo.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    SatelliteList: typeof import('./src/components/SatelliteList.vue')['default']
    SpaceGoal: typeof import('./src/components/SpaceGoal.vue')['default']
    StationState: typeof import('./src/components/Base/StationState.vue')['default']
    Title: typeof import('./src/components/Base/Title.vue')['default']
    WarningDisposal: typeof import('./src/components/WarningDisposal.vue')['default']
  }
}

export { }
